param(
    [string]$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path,
    [string]$SeedRoot = (Join-Path (Resolve-Path (Join-Path $PSScriptRoot '..')).Path 'transfer_seed\p201pro_2t2r_ascii_seed'),
    [string]$VendorRoot = 'G:\ROS开发\SDR P201P',
    [string]$DefaultAsciiTarget = 'C:\nx_fpga\p201pro_2t2r_sd_ready_work'
)

$ErrorActionPreference = 'Stop'

function Copy-PathItem {
    param(
        [Parameter(Mandatory=$true)][string]$Source,
        [Parameter(Mandatory=$true)][string]$Destination
    )

    if (-not (Test-Path -LiteralPath $Source)) {
        return
    }

    $parent = Split-Path -Parent $Destination
    if ($parent) {
        New-Item -ItemType Directory -Force -Path $parent | Out-Null
    }

    if ((Get-Item -LiteralPath $Source).PSIsContainer) {
        if (Test-Path -LiteralPath $Destination) {
            Remove-Item -LiteralPath $Destination -Recurse -Force
        }
        Copy-Item -LiteralPath $Source -Destination $Destination -Recurse -Force
    } else {
        Copy-Item -LiteralPath $Source -Destination $Destination -Force
    }
}

function Add-HashLine {
    param(
        [Parameter(Mandatory=$true)]$File,
        [Parameter(Mandatory=$true)][string]$Root,
        [Parameter(Mandatory=$true)]$Lines
    )
    $hash = Get-FileHash -LiteralPath $File.FullName -Algorithm SHA256
    $relative = $File.FullName.Substring($Root.Length).TrimStart('\')
    $Lines.Add("$($hash.Hash)  $relative")
}

if (Test-Path -LiteralPath $SeedRoot) {
    Remove-Item -LiteralPath $SeedRoot -Recurse -Force
}

New-Item -ItemType Directory -Force -Path $SeedRoot | Out-Null

$sourceItems = @(
    @{ Source='README.md'; Destination='README.md' },
    @{ Source='HANDOFF.md'; Destination='HANDOFF.md' },
    @{ Source='AGENTS.md'; Destination='AGENTS.md' },
    @{ Source='VERSION_ROUTE.md'; Destination='VERSION_ROUTE.md' },
    @{ Source='PROJECT_MAP.md'; Destination='PROJECT_MAP.md' },
    @{ Source='vivado2019_zynq7000_install_config.txt'; Destination='vivado2019_zynq7000_install_config.txt' },
    @{ Source='docs'; Destination='docs' },
    @{ Source='hdl'; Destination='src\hdl' },
    @{ Source='scripts'; Destination='src\scripts' },
    @{ Source='matlab'; Destination='src\matlab' },
    @{ Source='simulink'; Destination='src\simulink' },
    @{ Source='hdl_out'; Destination='src\hdl_out' },
    @{ Source='reports'; Destination='reports\existing_repo_reports' },
    @{ Source='vendor_matlab_demo_min'; Destination='vendor_matlab_demo_min' },
    @{ Source='deliverables\p201pro_2t2r_sd_project'; Destination='deliverables\p201pro_2t2r_sd_project' },
    @{ Source='deliverables\p201pro_2t2r_sd_project.zip'; Destination='deliverables\p201pro_2t2r_sd_project.zip' }
)

foreach ($item in $sourceItems) {
    Copy-PathItem -Source (Join-Path $RepoRoot $item.Source) -Destination (Join-Path $SeedRoot $item.Destination)
}

$vendorSourceLines = New-Object System.Collections.Generic.List[string]
$vendorSourceLines.Add('# Vendor Boot Reference Source Map')
$vendorSourceLines.Add('')
$vendorSourceLines.Add('These files are copied references only. They are not generated by this FPGA workspace and must not be treated as replacement boot artifacts without a reproduced build flow.')
$vendorSourceLines.Add('')

$vendorFiles = @()
if (Test-Path -LiteralPath $VendorRoot) {
    $vendorFiles = Get-ChildItem -LiteralPath $VendorRoot -Recurse -File -ErrorAction SilentlyContinue |
        Where-Object { $_.Name -match '(?i)^(BOOT\.bin|boot\.bin|devicetree\.dtb|fsbl\.elf)$' } |
        Sort-Object FullName
}

$vendorIndex = 1
foreach ($file in $vendorFiles) {
    $folder = 'ref_{0:D2}' -f $vendorIndex
    $destRel = Join-Path (Join-Path 'vendor_boot_refs' $folder) $file.Name
    $dest = Join-Path $SeedRoot $destRel
    Copy-PathItem -Source $file.FullName -Destination $dest
    $vendorSourceLines.Add('- `' + $destRel + '` <- `' + $file.FullName + '`')
    $vendorIndex++
}

if ($vendorFiles.Count -eq 0) {
    $vendorSourceLines.Add('- No vendor boot reference files were copied. Check VendorRoot manually.')
} else {
    $projectFiles = Get-ChildItem -LiteralPath $VendorRoot -Recurse -File -ErrorAction SilentlyContinue |
        Where-Object { $_.Name -match '(?i)(\.xpr$|\.bit$|\.bif$|\.xsa$|\.hdf$|\.xdc$)' } |
        Sort-Object FullName
    $vendorSourceLines.Add('')
    $vendorSourceLines.Add('Project/build-flow file scan:')
    if ($projectFiles.Count -eq 0) {
        $vendorSourceLines.Add('- No .xpr, .bit, .bif, .xsa, .hdf, or .xdc files were found in the vendor package scan.')
    } else {
        foreach ($file in $projectFiles) {
            $vendorSourceLines.Add('- FOUND `' + $file.FullName + '`')
        }
    }
}

New-Item -ItemType Directory -Force -Path (Join-Path $SeedRoot 'vendor_boot_refs') | Out-Null
$vendorSourceLines | Set-Content -LiteralPath (Join-Path $SeedRoot 'vendor_boot_refs\SOURCE_MAP.md') -Encoding UTF8

$copyScript = @'
param(
    [string]$Target = 'C:\nx_fpga\p201pro_2t2r_sd_ready_work'
)

$ErrorActionPreference = 'Stop'
$SeedRoot = Split-Path -Parent $MyInvocation.MyCommand.Path

New-Item -ItemType Directory -Force -Path $Target | Out-Null
Copy-Item -LiteralPath (Join-Path $SeedRoot '*') -Destination $Target -Recurse -Force

Write-Host "Copied P201Pro 2T2R ASCII workspace seed to: $Target"
Write-Host "Next:"
Write-Host "  cd $Target"
Write-Host "  & 'E:\Xilinx\Vivado\2019.1\bin\vivado.bat' -mode batch -nolog -nojournal -notrace -source src\scripts\list_xc7z_parts.tcl"
Write-Host "  & 'E:\Xilinx\Vivado\2019.1\bin\vivado.bat' -mode batch -source src\scripts\vivado_synth_stream_wrapper.tcl"
'@
$copyScript | Set-Content -LiteralPath (Join-Path $SeedRoot 'copy_to_ascii_workspace.ps1') -Encoding UTF8

$readmeLines = @(
    '# P201Pro 2T2R ASCII Workspace Seed',
    '',
    'Generated: ' + (Get-Date -Format 'yyyy-MM-dd HH:mm:ss zzz'),
    '',
    'This directory is staged inside the NX development workspace so it can be moved to an ASCII-only Vivado working path later.',
    '',
    'Recommended target:',
    '',
    '```text',
    $DefaultAsciiTarget,
    '```',
    '',
    'Use:',
    '',
    '```powershell',
    "powershell -NoProfile -ExecutionPolicy Bypass -File .\copy_to_ascii_workspace.ps1 -Target '$DefaultAsciiTarget'",
    '```',
    '',
    'Then run Vivado from the ASCII target path.',
    '',
    'Important safety notes:',
    '',
    '- This seed does not modify the original SD directory: C:\Users\20642\Desktop\开发\SDR\2r2t.',
    '- Vendor boot files under vendor_boot_refs\ are reference copies only.',
    '- Do not copy any BOOT.bin from this seed to a real/original SD card as a replacement.',
    '- The current verified direction is to synthesize the low-IO wrapper first, then integrate into a copied P201Pro/Vivado boot flow.',
    '',
    'Main contents:',
    '',
    '- src\hdl\: new low-IO wrapper source.',
    '- src\scripts\: Vivado/MATLAB helper scripts.',
    '- src\hdl_out\: existing HDL Coder generated feasibility core.',
    '- deliverables\p201pro_2t2r_sd_project\: existing non-bootable engineering package.',
    '- vendor_boot_refs\: copied vendor boot baseline artifacts and source map.',
    '- reports\existing_repo_reports\: existing validation reports.',
    '- HASHES.sha256: SHA256 for every staged file.',
    '- MANIFEST.md: file inventory with sizes.',
    '',
    'Next stage after moving:',
    '',
    '1. Verify xc7z020clg400-1 from ASCII path.',
    '2. Run wrapper synthesis from ASCII path.',
    '3. Record utilization/timing.',
    '4. Package wrapper as IP or integrate into a copied vendor/ADI AD9361 reference design.',
    '5. Only generate bitstream/BOOT.bin after the copied board project is reproducible.'
)
$readmeLines | Set-Content -LiteralPath (Join-Path $SeedRoot 'README.md') -Encoding UTF8

$manifestLines = New-Object System.Collections.Generic.List[string]
$manifestLines.Add('# P201Pro 2T2R ASCII Workspace Seed Manifest')
$manifestLines.Add('')
$manifestLines.Add("Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss zzz')")
$manifestLines.Add('')
$manifestLines.Add('Seed root: `' + $SeedRoot + '`')
$manifestLines.Add('')
$manifestLines.Add('| Path | Bytes |')
$manifestLines.Add('| --- | ---: |')

$hashLines = New-Object System.Collections.Generic.List[string]
Get-ChildItem -LiteralPath $SeedRoot -Recurse -File |
    Sort-Object FullName |
    ForEach-Object {
        $rel = $_.FullName.Substring($SeedRoot.Length).TrimStart('\')
        $manifestLines.Add('| `' + $rel + '` | ' + $_.Length + ' |')
        if ($rel -ne 'HASHES.sha256') {
            Add-HashLine -File $_ -Root $SeedRoot -Lines $hashLines
        }
    }

$manifestLines | Set-Content -LiteralPath (Join-Path $SeedRoot 'MANIFEST.md') -Encoding UTF8
$hashLines | Set-Content -LiteralPath (Join-Path $SeedRoot 'HASHES.sha256') -Encoding ASCII
Start-Sleep -Milliseconds 500

$zipPath = Join-Path (Split-Path -Parent $SeedRoot) 'p201pro_2t2r_ascii_seed.zip'
if (Test-Path -LiteralPath $zipPath) {
    Remove-Item -LiteralPath $zipPath -Force
}
Compress-Archive -LiteralPath $SeedRoot -DestinationPath $zipPath -Force

Write-Host "Seed created: $SeedRoot"
Write-Host "Seed zip: $zipPath"
