repoRoot = fileparts(fileparts(mfilename("fullpath")));
reportsDir = fullfile(repoRoot, "reports");
hdlOutDir = fullfile(repoRoot, "hdl_out", "builtin_power");
modelDir = fullfile(repoRoot, "simulink");
if ~exist(reportsDir, "dir"), mkdir(reportsDir); end
if ~exist(hdlOutDir, "dir"), mkdir(hdlOutDir); end
if ~exist(modelDir, "dir"), mkdir(modelDir); end

reportPath = fullfile(reportsDir, "builtin_power_hdl_generation.txt");
if exist(reportPath, "file"), delete(reportPath); end
diary(reportPath);
fprintf("P201Pro built-in block power HDL generation\n");
fprintf("Generated: %s\n", datestr(now, 31));
fprintf("MATLAB version: %s\n\n", version);

modelName = "p201pro_builtin_power_hdl_model";
modelPath = fullfile(modelDir, modelName + ".slx");
if bdIsLoaded(modelName), close_system(modelName, 0); end
if exist(modelPath, "file"), delete(modelPath); end

new_system(modelName);
open_system(modelName);
set_param(modelName, "Solver", "FixedStepDiscrete", "FixedStep", "1", "StopTime", "1");
hdlsetup(modelName);

add_block("simulink/Sources/In1", modelName + "/iBin", ...
    "Position", [40 55 70 75], ...
    "OutDataTypeStr", "fixdt(1,16,14)", ...
    "PortDimensions", "64", ...
    "SampleTime", "1");
add_block("simulink/Sources/In1", modelName + "/qBin", ...
    "Position", [40 155 70 175], ...
    "OutDataTypeStr", "fixdt(1,16,14)", ...
    "PortDimensions", "64", ...
    "SampleTime", "1");
add_block("simulink/Math Operations/Product", modelName + "/i_square", ...
    "Position", [145 40 190 90], ...
    "Inputs", "2", ...
    "Multiplication", "Element-wise(.*)", ...
    "OutDataTypeStr", "fixdt(1,40,28)");
add_block("simulink/Math Operations/Product", modelName + "/q_square", ...
    "Position", [145 140 190 190], ...
    "Inputs", "2", ...
    "Multiplication", "Element-wise(.*)", ...
    "OutDataTypeStr", "fixdt(1,40,28)");
add_block("simulink/Math Operations/Sum", modelName + "/power_bins", ...
    "Position", [260 85 305 145], ...
    "Inputs", "++", ...
    "OutDataTypeStr", "fixdt(1,40,28)");
add_block("simulink/Math Operations/MinMax", modelName + "/peak_power", ...
    "Position", [375 75 425 115], ...
    "Function", "max", ...
    "Inputs", "1", ...
    "OutDataTypeStr", "fixdt(1,40,28)");
add_block("simulink/Math Operations/Sum", modelName + "/sum_power", ...
    "Position", [375 145 425 185], ...
    "Inputs", "+", ...
    "CollapseMode", "All dimensions", ...
    "AccumDataTypeStr", "fixdt(1,48,28)", ...
    "OutDataTypeStr", "fixdt(1,48,28)");
add_block("simulink/Sinks/Out1", modelName + "/psdBins", ...
    "Position", [520 60 550 80]);
add_block("simulink/Sinks/Out1", modelName + "/peakPower", ...
    "Position", [520 100 550 120]);
add_block("simulink/Sinks/Out1", modelName + "/sumPower", ...
    "Position", [520 160 550 180]);

add_line(modelName, "iBin/1", "i_square/1");
add_line(modelName, "iBin/1", "i_square/2");
add_line(modelName, "qBin/1", "q_square/1");
add_line(modelName, "qBin/1", "q_square/2");
add_line(modelName, "i_square/1", "power_bins/1");
add_line(modelName, "q_square/1", "power_bins/2");
add_line(modelName, "power_bins/1", "psdBins/1");
add_line(modelName, "power_bins/1", "peak_power/1");
add_line(modelName, "power_bins/1", "sum_power/1");
add_line(modelName, "peak_power/1", "peakPower/1");
add_line(modelName, "sum_power/1", "sumPower/1");

set_param(modelName, "SimulationCommand", "Update");
save_system(modelName, modelPath);
fprintf("MODEL_CREATED %s\n", modelPath);

try
    checkhdl(char(modelName));
    fprintf("CHECKHDL=PASS\n");
catch ME
    fprintf("CHECKHDL=FAIL\n%s\n", getReport(ME, "basic"));
end

try
    makehdl(char(modelName), ...
        "TargetLanguage", "Verilog", ...
        "TargetDirectory", hdlOutDir, ...
        "GenerateHDLTestBench", "off");
    fprintf("MAKEHDL=PASS\n");
catch ME
    fprintf("MAKEHDL=FAIL\n%s\n", getReport(ME, "basic"));
end

save_system(modelName, modelPath);
close_system(modelName, 0);
diary off;
