set script_dir [file dirname [file normalize [info script]]]
set repo_dir [file dirname $script_dir]
set proj_dir [file join $repo_dir vendor_experiments PZ_PZP201_PRO_NO_OS_ACCEL]
set xpr [file join $proj_dir PZ_PZP201_PRO_NO_OS.xpr]
set cdc_xdc [file join $repo_dir hdl p201pro_ad9361_power_tap_cdc.xdc]
set reports_dir [file join $repo_dir reports stage4_ad9361_tap_bitstream_physopt_v8d1_incremental_auto_roll_fix]
set report_file [file join $reports_dir bitstream_physopt_report.md]
file mkdir $reports_dir

open_project $xpr
open_run impl_1 -name impl_1
source $cdc_xdc

set physopt_status PASS
set physopt_text ""
if {[catch {phys_opt_design -directive AggressiveExplore} physopt_text]} {
    set physopt_status "FAILED: $physopt_text"
}

set route_status PASS
set route_text ""
if {[catch {route_design -directive Explore} route_text]} {
    set route_status "FAILED: $route_text"
}

set bit_dst [file join $reports_dir system_top_with_p201_tap_v8d1_incremental_auto_roll_fix_physopt.bit]
set dcp_dst [file join $reports_dir system_top_with_p201_tap_v8d1_incremental_auto_roll_fix_physopt_impl.dcp]
set hwdef_dst [file join $reports_dir system_top_with_p201_tap_v8d1_incremental_auto_roll_fix_physopt.hwdef]

report_utilization -file [file join $reports_dir utilization_impl.txt]
report_timing_summary -file [file join $reports_dir timing_summary_impl.txt]
report_route_status -file [file join $reports_dir route_status_impl.txt]
report_drc -file [file join $reports_dir drc_impl.txt]
write_checkpoint -force $dcp_dst

set bit_status PASS
set bit_text ""
if {[catch {write_bitstream -force $bit_dst} bit_text]} {
    set bit_status "FAILED: $bit_text"
}

set hwdef_status PASS
set hwdef_text ""
if {[catch {write_hwdef -force -file $hwdef_dst} hwdef_text]} {
    set hwdef_status "FAILED: $hwdef_text"
}

set fh [open $report_file w]
puts $fh "# Integrated AD9361 Tap Post-Route PhysOpt Report V8D1 Incremental Auto-Roll Fix"
puts $fh ""
puts $fh "Generated: [clock format [clock seconds] -format {%Y-%m-%d %H:%M:%S}]"
puts $fh ""
puts $fh "- Project: `$xpr`"
puts $fh "- Opened run: `impl_1`"
puts $fh "- phys_opt_design: `$physopt_status`"
puts $fh "- route_design: `$route_status`"
puts $fh "- Bitstream write: `$bit_status`"
puts $fh "- Bitstream: `$bit_dst`"
puts $fh "- Implemented checkpoint: `$dcp_dst`"
puts $fh "- HWDEF export: `$hwdef_status`"
puts $fh "- HWDEF file: `$hwdef_dst`"
puts $fh "- V8D1 intent: post-route physopt gate for V8L2 logic using V8L1-referenced incremental implementation when possible"
puts $fh ""
puts $fh "No BOOT.bin or SD payload was generated by this script."
close $fh

puts "PHYSOPT_REPORT=$report_file"
puts "PHYSOPT_STATUS=$physopt_status"
puts "ROUTE_STATUS=$route_status"
puts "BIT_STATUS=$bit_status"
puts "BITSTREAM=$bit_dst"
puts "HWDEF_STATUS=$hwdef_status"
close_project
