set script_dir [file dirname [file normalize [info script]]]
set repo_dir [file dirname $script_dir]
set proj_dir [file join $repo_dir vendor_experiments PZ_PZP201_PRO_NO_OS_ACCEL]
set xpr [file join $proj_dir PZ_PZP201_PRO_NO_OS.xpr]
set bd [file join $proj_dir PZ_PZP201_PRO_NO_OS.srcs sources_1 bd system system.bd]
set vendor_library [file join $proj_dir library]
set local_ip_repo [file join $repo_dir vivado ip_repo]
set cdc_xdc [file join $repo_dir hdl p201pro_ad9361_power_tap_cdc.xdc]
set reference_dcp [file join $repo_dir reports stage4_ad9361_tap_bitstream_physopt_v8l1_auto_agg system_top_with_p201_tap_v8l1_auto_agg_physopt_impl.dcp]
set reports_dir [file join $repo_dir reports stage4_ad9361_tap_bitstream_v8d1_incremental_auto_roll_fix]
set report_file [file join $reports_dir bitstream_report.md]
file mkdir $reports_dir

open_project $xpr
set_property ip_repo_paths [list $vendor_library $local_ip_repo] [current_project]
update_ip_catalog
open_bd_design $bd

if {[llength [get_files -quiet $cdc_xdc]] == 0} {
    add_files -fileset constrs_1 -norecurse $cdc_xdc
}
set_property used_in {synthesis implementation} [get_files $cdc_xdc]

set validate_status PASS
set validate_text ""
if {[catch {validate_bd_design} validate_text]} {
    set validate_status FAILED
}

generate_target all [get_files $bd]
export_ip_user_files -of_objects [get_files $bd] -no_script -sync -force -quiet

reset_run synth_1
launch_runs synth_1 -jobs 4
wait_on_run synth_1

reset_run impl_1
set incremental_status "SKIPPED: reference checkpoint not found"
if {[file exists $reference_dcp]} {
    if {[catch {set_property incremental_checkpoint $reference_dcp [get_runs impl_1]} incremental_text]} {
        set incremental_status "FAILED: $incremental_text"
    } else {
        set incremental_status "PASS"
    }
}
launch_runs impl_1 -to_step write_bitstream -jobs 4
wait_on_run impl_1

set synth_status [get_property STATUS [get_runs synth_1]]
set synth_progress [get_property PROGRESS [get_runs synth_1]]
set impl_status [get_property STATUS [get_runs impl_1]]
set impl_progress [get_property PROGRESS [get_runs impl_1]]

set bit_src [file join $proj_dir PZ_PZP201_PRO_NO_OS.runs impl_1 system_top.bit]
set bit_dst [file join $reports_dir system_top_with_p201_tap_v8d1_incremental_auto_roll_fix.bit]
set hwdef_dst [file join $reports_dir system_top_with_p201_tap_v8d1_incremental_auto_roll_fix.hwdef]
set dcp_dst [file join $reports_dir system_top_with_p201_tap_v8d1_incremental_auto_roll_fix_impl.dcp]
set bit_exists [file exists $bit_src]

if {[string match "*Complete*" $impl_status]} {
    open_run impl_1 -name impl_1
    source $cdc_xdc
    report_utilization -file [file join $reports_dir utilization_impl.txt]
    report_timing_summary -file [file join $reports_dir timing_summary_impl.txt]
    report_route_status -file [file join $reports_dir route_status_impl.txt]
    report_drc -file [file join $reports_dir drc_impl.txt]
    write_checkpoint -force $dcp_dst
    if {$bit_exists} {
        file copy -force $bit_src $bit_dst
    }
    if {[catch {write_hwdef -force -file $hwdef_dst} hwdef_error]} {
        set hwdef_status "FAILED: $hwdef_error"
    } else {
        set hwdef_status "PASS"
    }
} else {
    set hwdef_status "SKIPPED"
}

set fh [open $report_file w]
puts $fh "# Integrated AD9361 Tap Bitstream Report V8D1 Incremental Auto-Roll Fix"
puts $fh ""
puts $fh "Generated: [clock format [clock seconds] -format {%Y-%m-%d %H:%M:%S}]"
puts $fh ""
puts $fh "- Project: `$xpr`"
puts $fh "- BD: `$bd`"
puts $fh "- validate_bd_design: `$validate_status`"
puts $fh "- Synthesis status: `$synth_status`"
puts $fh "- Synthesis progress: `$synth_progress`"
puts $fh "- Implementation status: `$impl_status`"
puts $fh "- Implementation progress: `$impl_progress`"
puts $fh "- Incremental reference checkpoint: `$reference_dcp`"
puts $fh "- Incremental checkpoint setup: `$incremental_status`"
puts $fh "- Source bitstream: `$bit_src`"
puts $fh "- Copied bitstream: `$bit_dst`"
puts $fh "- Bitstream exists: `$bit_exists`"
puts $fh "- Implemented checkpoint: `$dcp_dst`"
puts $fh "- HWDEF export: `$hwdef_status`"
puts $fh "- HWDEF file: `$hwdef_dst`"
puts $fh "- V8D1 intent: PC artifact gate for V8L2 logic using V8L1-referenced incremental implementation when possible"
puts $fh ""
puts $fh "No BOOT.bin or SD payload was generated by this script."
close $fh

puts "BITSTREAM_REPORT=$report_file"
puts "VALIDATE_BD_DESIGN=$validate_status"
puts "SYNTH_STATUS=$synth_status"
puts "SYNTH_PROGRESS=$synth_progress"
puts "IMPL_STATUS=$impl_status"
puts "IMPL_PROGRESS=$impl_progress"
puts "INCREMENTAL_REFERENCE=$reference_dcp"
puts "INCREMENTAL_STATUS=$incremental_status"
puts "BITSTREAM=$bit_dst"
puts "BITSTREAM_EXISTS=$bit_exists"
puts "HWDEF_STATUS=$hwdef_status"
close_project
