set script_dir [file dirname [file normalize [info script]]]
set repo_dir [file dirname $script_dir]
set proj_dir [file join $repo_dir vendor_experiments PZ_PZP201_PRO_NO_OS_ACCEL]
set xpr [file join $proj_dir PZ_PZP201_PRO_NO_OS.xpr]
set bd [file join $proj_dir PZ_PZP201_PRO_NO_OS.srcs sources_1 bd system system.bd]
set vendor_library [file join $proj_dir library]
set local_ip_repo [file join $repo_dir vivado ip_repo]
set cdc_xdc [file join $repo_dir hdl p201pro_ad9361_power_tap_cdc.xdc]
set reports_dir [file join $repo_dir reports stage4_ad9361_tap_integrated_synth]
set report_file [file join $reports_dir integrated_synth_report.md]
file mkdir $reports_dir

open_project $xpr
set_property ip_repo_paths [list $vendor_library $local_ip_repo] [current_project]
update_ip_catalog
open_bd_design $bd

if {[llength [get_files -quiet $cdc_xdc]] == 0} {
    add_files -fileset constrs_1 -norecurse $cdc_xdc
}
set_property used_in {synthesis implementation} [get_files $cdc_xdc]

set validate_status PASS
set validate_text ""
if {[catch {validate_bd_design} validate_text]} {
    set validate_status FAILED
}

generate_target all [get_files $bd]
export_ip_user_files -of_objects [get_files $bd] -no_script -sync -force -quiet

reset_run synth_1
launch_runs synth_1 -jobs 4
wait_on_run synth_1
set synth_status [get_property STATUS [get_runs synth_1]]
set synth_progress [get_property PROGRESS [get_runs synth_1]]

set synth_ok [expr {[string match "*Complete*" $synth_status]}]
if {$synth_ok} {
    open_run synth_1 -name synth_1
    source $cdc_xdc
    report_utilization -file [file join $reports_dir utilization.txt]
    report_timing_summary -file [file join $reports_dir timing_summary.txt]
    write_checkpoint -force [file join $reports_dir system_top_with_p201_tap_synth.dcp]
}

set fh [open $report_file w]
puts $fh "# Integrated AD9361 Tap Synthesis Report"
puts $fh ""
puts $fh "Generated: [clock format [clock seconds] -format {%Y-%m-%d %H:%M:%S}]"
puts $fh ""
puts $fh "- Project: `$xpr`"
puts $fh "- BD: `$bd`"
puts $fh "- validate_bd_design: `$validate_status`"
puts $fh "- Synthesis status: `$synth_status`"
puts $fh "- Synthesis progress: `$synth_progress`"
puts $fh "- Synthesis checkpoint: `[file join $reports_dir system_top_with_p201_tap_synth.dcp]`"
puts $fh ""
puts $fh "No implementation, bitstream, BOOT.bin, or SD payload was generated by this script."
close $fh

puts "INTEGRATED_SYNTH_REPORT=$report_file"
puts "VALIDATE_BD_DESIGN=$validate_status"
puts "SYNTH_STATUS=$synth_status"
puts "SYNTH_PROGRESS=$synth_progress"
close_project
