FROM debian:bookworm-slim

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        file \
        gcc-arm-linux-gnueabihf \
        libc6-dev-armhf-cross \
        make \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /work/sdr-system/sdrd
